### ISSUE TITLE
Serial operation queue factory

### ISSUE THREAD

**Issue by wnagrodzki** [TriforkKRK/TFFoundation#11]
```swift
extension OperationQueue {
    static func makeSerial() -> OperationQueue {
        let queue = OperationQueue()
        queue.maxConcurrentOperationCount = 1
        return queue
    }
}
```

It allows creating serial queuing in one line
```swift
class A {
    let isolationQueue = OperaitonQueue.makeSerial()
}
```

**Comment by wnagrodzki** [comment]
@pwgr @Moskacz Do you see it as useful?

**Comment by Moskacz** [comment]
Yes, but at the same time I think `createSerial()` would be more self describing. What do you think?

**Comment by wnagrodzki** [comment]
@Moskacz I used `make` prefix to conform to [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/).
> Begin names of factory methods with “make”, e.g. x.makeIterator().

**Comment by Moskacz** [comment]
@wnagrodzki OK, you're right.

**Comment by wnagrodzki** [comment]
Implemented
